require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

# use_frameworks! :linkage => :static
use_modular_headers!

# Convert all permission pods into static libraries
# pre_install do |installer|
#   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

#   installer.pod_targets.each do |pod|
#     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
#       def pod.build_type;
#         # Uncomment the line corresponding to your CocoaPods version
#         # Pod::BuildType.static_library # >= 1.9
#         Pod::Target::BuildType.static_library # < 1.9
#       end
#     end
#   end
# end

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

target 'UpPark' do
  permissions_path = '../node_modules/react-native-permissions/ios'


  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GoogleMaps'

  pod 'react-native-maps', path: '../node_modules/react-native-maps'

  pod 'Google-Maps-iOS-Utils', '~> 4.1.0'

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"


  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'UpParkTests' do
    inherit! :complete
    # Pods for testing
  end



  # post_install do |installer|
  #   react_native_post_install(
  #     installer,
  #     # Set `mac_catalyst_enabled` to `true` in order to apply patches
  #     # necessary for Mac Catalyst builds
  #     :mac_catalyst_enabled => false
  #   )
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end

  # use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })

  post_install do |installer|
    # Build Active Architecture Only "NO" (react-native-maps)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set the deployment target for all pods
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
        
        # Existing settings (example: setting ONLY_ACTIVE_ARCH)
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
